<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SeedServices extends Migration {

    private $services = array(
        "Air Duct Cleaning",
        "Alarms",
        "Animal Removal",
        "Apartments",
        "Appliance Refinishing",
        "Appliance Repair - Large",
        "Appliance Repair - Small",
        "Appraisals - Real Estate",
        "Architects & Building Design",
        "Asbestos Removal",
        "Auction Services",
        "Awnings",
        "Basement Waterproofing",
        "Bathtub Refinishing & Liners",
        "Builders - Garages/Barns/Sheds",
        "Builders - Homes",
        "Cabinet Making",
        "Cabinet Refacing/Restoration",
        "Carpentry - Unfinished",
        "Carpentry - Woodworking",
        "Carpet Sales/Installation/Repair",
        "Ceiling Fans",
        "Central Vacuum Cleaning",
        "Ceramic Tile",
        "Chimney Caps",
        "Chimney Repair",
        "Chimney Sweep",
        "Closets",
        "Concrete - Leveling/Mudjacking",
        "Concrete - Pouring & Repair",
        "Concrete - Stamped & Decorative",
        "Countertops",
        "Deck Maintenance",
        "Decks & Porches",
        "Doors",
        "Drain Pipe Installation - Exterior",
        "Driveways - Asphalt",
        "Driveways - Concrete",
        "Drywall",
        "Electrical",
        "Energy Efficiency Auditing",
        "Epoxy Flooring",
        "Excavating",
        "Fencing",
        "Fencing & Driveway Gates",
        "Fireplaces",
        "Firewood",
        "Flooring Sales/Installation/Repair",
        "Foundation Repair",
        "Fountains",
        "Framing",
        "Furniture - Refinishing & Repair",
        "Garage Doors",
        "Gas Leak Repair",
        "Gas Logs",
        "Generator",
        "Glass & Mirrors",
        "Glass Block",
        "Greenhouses/Nurseries",
        "Gutter Cleaning",
        "Gutter Repair & Replacement",
        "Handymen",
        "Hardware & Home Improvement Stores",
        "Hardwood Flooring Sales/Installation/Refinishing",
        "Heating & A/C",
        "Heating Oil",
        "Home Automation",
        "Home Inspection",
        "Home Staging",
        "Insulation",
        "Interior Design & Decorating",
        "Land Surveying",
        "Landscaping",
        "Landscaping & Lighting",
        "Landscaping - Hardscaping & Pavers",
        "Landscaping - Lakefront",
        "Lawn & Yard Work",
        "Lawn Fertilization & Treatment",
        "Lawn Irrigation",
        "Lawn Mower & Power Tool Repair",
        "Lead Testing & Removal",
        "Leaf Removal",
        "Lighting",
        "Locksmiths",
        "Marble & Granite",
        "Masonry",
        "Misting Systems",
        "Mold Testing & Remediation",
        "Mortgage Companies",
        "Moving",
        "Mulch & Topsoil",
        "Organization - Home & Garage",
        "Painting - Exterior",
        "Painting - Interior",
        "Pest Control/Exterminating",
        "Plastering",
        "Playground Equipment",
        "Plumbing",
        "Plumbing - Drain Cleaning",
        "Pool & Spa Service",
        "Pressure Washing",
        "Propane Sales/Services",
        "Property Management",
        "Radon Detection & Reduction",
        "Real Estate Agents",
        "Remodeling - Basements",
        "Remodeling - General",
        "Remodeling - Kitchen & Bathroom",
        "Remodeling - Modular & Mobile Home",
        "Remodeling - Sunrooms & Patio Enclosures",
        "Roof Cleaning",
        "Roofing",
        "Roto-Tilling",
        "Screen Repair",
        "Septic Tank",
        "Sewer Cleaning",
        "Siding",
        "Skylights",
        "Solar Panels",
        "Stone & Gravel",
        "Storage Facilities",
        "Structural Engineering",
        "Stucco",
        "Title Companies",
        "Tree Service",
        "Wallpaper Removal",
        "Wallpapering",
        "Warranty Companies - Home",
        "Water & Smoke Damage",
        "Water Heaters",
        "Water Softeners",
        "Wells & Pumps",
        "Window Tinting",
        "Window Treatments",
        "Windows",
        "Windows - Egress",
        "Windows - Safety & Security Film",
        "Wrought Iron",
        "Auto Accessories",
        "Auto Alarms",
        "Auto Body Work",
        "Auto Detailing",
        "Auto Glass",
        "Auto Inspections",
        "Auto Mufflers",
        "Auto Painting",
        "Auto Radiators",
        "Auto Radio Service",
        "Auto Sales",
        "Auto Service",
        "Auto Tires",
        "Auto Towing",
        "Auto Transmission",
        "Auto Transportation",
        "Car Washes",
        "Allergy & Immunology",
        "Allergy & Immunology - Pediatrics",
        "Alternative Med. - Acupuncture",
        "Alternative Med. - General",
        "Alternative Med. - Hypnotherapy",
        "Alternative Med. - Traditional Chinese Medicine",
        "Ambulance Services",
        "Anesthesiology",
        "Blood Care/Hematology",
        "Blood Care/Hematology - Pediatrics",
        "Cancer/Oncology",
        "Cancer/Oncology - Pediatric",
        "Chest/Thoracic Surgery",
        "Chest/Thoracic Surgery - Pediatrics",
        "Chiropractic Care",
        "Counseling - Addiction",
        "Counseling - Family",
        "Counseling - General",
        "Counseling - Grief",
        "Counseling - Marriage/Relationship",
        "Dentistry - Cosmetic",
        "Dentistry - Denture Labs",
        "Dentistry - Dentures/Prosthodontics",
        "Dentistry - General",
        "Dentistry - Gum Care/Periodontics",
        "Dentistry - Oral & Maxillofacial Surgery",
        "Dentistry - Orthodontics",
        "Dentistry - Pediatrics",
        "Dentistry - Root Canals/Endodontics",
        "Dentistry - TMJ",
        "Dermatology - General",
        "Dermatology - Laser Skin Treatment",
        "Dermatology - Pediatrics",
        "Digestive Care/Gastroenterology",
        "Digestive Care/Gastroenterology - Pediatrics",
        "Ear Nose & Throat - Hearing Aids",
        "Ear Nose & Throat - Hearing Tests/Audiology",
        "Ear, Nose & Throat - Pediatrics",
        "Ear, Nose & Throat/Otolaryngology",
        "Endocrinology & Metabolism",
        "Endocrinology & Metabolism - Pediatrics",
        "Eye Care - LASIK",
        "Eye Care - Ophthalmology",
        "Eye Care - Optical Sales & Repair",
        "Eye Care - Optometry",
        "Eye Care - Pediatric Ophthalmology",
        "Eye Care - Pediatric Optometry",
        "Fitness - Centers",
        "Fitness - Equipment",
        "Fitness - Training",
        "Foot Care - Podiatry",
        "Foot Care - Prosthetics & Orthotics",
        "Gastroenterology - Colon & Rectal Care",
        "General Surgery",
        "General Surgery - Pediatrics",
        "Genetic Medicine",
        "Hair - Replacement & Transplants",
        "Hair Removal",
        "Health Education/Workshops",
        "Health Insurance - Agents & Companies",
        "Health Insurance - Brokers",
        "Heart Care - Cardiovascular Surgery",
        "Heart Care - General Cardiology",
        "Heart Care - Interventional Cardiology",
        "Heart Care - Pediatric Cardiology",
        "Heart Care - Pediatric Cardiovascular Surgery",
        "Home Healthcare - Disability Equipment & Services",
        "Home Healthcare - Hospice",
        "Home Healthcare - In-home Services",
        "Home Healthcare - Independent Living",
        "Home Healthcare - Medical Alert Systems",
        "Home Healthcare - Medical Equipment & Services",
        "Hospitalist",
        "Hospitals - Children's",
        "Hospitals - Emergency Medicine",
        "Hospitals - General",
        "Hospitals - Intensive Care",
        "Imaging & Pediatric Radiology",
        "Imaging - Radiology",
        "Imaging - Ultrasound Diagnostics",
        "Infectious Diseases",
        "Kidney Care/nephrology",
        "Kidney Care/nephrology - Pediatrics",
        "Lab Services - Blood Banks",
        "Lab Services - Blood Work",
        "Lab Services - Diagnostic",
        "Lab Services - Drug & Alcohol Testing",
        "Liver Care/Hepatology",
        "Longterm Care - Adult Daycare",
        "Longterm Care - Assisted Living",
        "Longterm Care - Hospice Facilities",
        "Longterm Care - Nursing Homes",
        "Lung/Pulmonology",
        "Lung/Pulmonology & Pediatrics",
        "Massage Therapy",
        "Massage Therapy - Reflexology",
        "Medical Spa",
        "Mental Health - Alcohol Treatment Centers",
        "Mental Health - Drug Abuse Treatment Centers",
        "Mental Health - Psychiatry",
        "Mental Health - Psychology",
        "Neuroscience - Neurology",
        "Neuroscience - Neurosurgery",
        "Neuroscience - Pediatric Neurology",
        "Nurse Practitioners",
        "Orthopedics",
        "Orthopedics - Foot & Ankle",
        "Orthopedics - Hand & Wrist",
        "Orthopedics - Hips",
        "Orthopedics - Knee & Leg",
        "Orthopedics - Pediatrics",
        "Orthopedics - Shoulder & Arm",
        "Orthopedics - Spine & Neck",
        "Otolaryngology",
        "Outpatient Centers - Urgent Care",
        "Pain Management",
        "Patient Advocates",
        "Pediatrics - Primary Care",
        "Pharmacies",
        "Plastic Surgery - Cosmetic",
        "Plastic Surgery - Reconstructive",
        "Primary Care - Family Medicine",
        "Primary Care - Geriatrics",
        "Primary Care - Internal Medicine",
        "Primary Care - Osteopathic Medicine",
        "Rehabilitation - Occupational Therapy",
        "Rehabilitation - Physical Medicine & Rehab",
        "Rehabilitation - Physical Therapy",
        "Rheumatology",
        "Rheumatology - Pediatrics",
        "Skin & Body Care - Aromatherapy",
        "Skin & Body Care - Colonic Irrigation",
        "Skin & Body Care - Day Spa Services",
        "Skin & Body Care - Vein Treatment",
        "Sleep Medicine",
        "Speech Therapy",
        "Sports Medicine",
        "Sports Medicine - Pediatrics",
        "Telemedicine",
        "Transplant Surgery",
        "Travel Medicine",
        "Urology",
        "Urology - Pediatric Urology",
        "Vascular Surgery",
        "Weight Mgt. - Bariatric Medicine",
        "Weight Mgt. - Dietitians/Nutritionists",
        "Weight management - Vitamin & Supplement Stores",
        "Weight management - Weight Loss Programs",
        "Women's Services - Breast Surgery",
        "Women's Services - Doulas",
        "Women's Services - Obstetrics & Gynecology",
        "Women's services - Birth Control & Family Planning",
        "Women's services - Fertility",
        "Women's services - Midwives",
        "Animal & House Sitting",
        "Animal Boarding Kennels",
        "Animal Breeders/Brokers",
        "Animal Burial/Cremation",
        "Animal Fencing",
        "Animal Grooming",
        "Animal Rescues/Shelters",
        "Animal Training",
        "Aquariums",
        "Dog Walking",
        "Pet Bakeries",
        "Pet Insurance",
        "Pet Stores",
        "Pooper Scoopers",
        "Veterinarians",
        "Accountants/Tax Consultants",
        "Alterations/Sewing/Decorating",
        "Antiques",
        "Baby Equipment Rental",
        "Banking/Credit Unions",
        "Basketball Goals",
        "Bicycles",
        "Billiard Table Repair",
        "Billiard Table Sales",
        "Biohazard Remediation",
        "Blind Cleaning",
        "Boats",
        "Bridal Shops",
        "Buffing & Polishing",
        "Buying Services",
        "Cake Decorating",
        "Calligraphy",
        "Camcorder Repair",
        "Camera Repair",
        "Career Coach",
        "Carpet Cleaning",
        "Catering",
        "Chefs",
        "Child Care - Center",
        "Child Care - Family/In Provider Home",
        "Child Care - Other",
        "Childproofing",
        "China Repair",
        "Cleaning",
        "Clock Repair",
        "Computer Repair & Services",
        "Computer Sales",
        "Computer Training",
        "Cooking Classes",
        "Costume Rental",
        "Credit Repair",
        "Dance Instruction",
        "Delivery Service",
        "Dermatology - General",
        "Dermatology - Laser Skin Treatment",
        "Dermatology - Pediatrics",
        "Dock Building & Repair",
        "Drapery Cleaning",
        "Drivers Education",
        "Dry Cleaning",
        "Dryer Vent Cleaning",
        "Dumpster Service",
        "Earthquake Retrofitting",
        "Electronic Gadget Repair",
        "Entertainment/Parties",
        "Errands",
        "Film Developing",
        "Financial Planning",
        "Floor Cleaning/Polishing/Waxing",
        "Florists",
        "Funeral Homes",
        "Furniture - Custom Made",
        "Furniture - Refinishing & Repair",
        "Furniture - Sales",
        "Furs",
        "Garbage Collection",
        "Gas Grill Repair",
        "Gas Leak Repair",
        "Genealogy",
        "Gifts",
        "Graphic Design",
        "Guns",
        "Hair - Replacement & Transplants",
        "Hair Removal",
        "Hair Salons/Barbers",
        "Hauling",
        "Holiday Decorating",
        "Housecleaning",
        "Hurricane Shutters",
        "Insurance Agencies",
        "Internet Service",
        "Ironing",
        "Jewelry Sales/Design/Repair",
        "Lamp Repair",
        "Leather & Vinyl Repair",
        "Life Coaches",
        "Limousine Service",
        "Luggage Repair",
        "Mailbox Repair",
        "Mailing Service",
        "Manicures/Nails",
        "Marinas",
        "Mattresses",
        "Medical Spa",
        "Metal Fabrication & Restoration",
        "Motorcycle Service",
        "Music Instruction",
        "Musical Instrument Repair",
        "Notary",
        "Office Equipment Repair",
        "Oriental Rug Cleaning",
        "Paper Shredding",
        "Phone Repair",
        "Phone Sales",
        "Phone Service - Cellular",
        "Phone Service - Landline",
        "Phone Wiring",
        "Photography",
        "Piano Moving",
        "Piano Tuning",
        "Plastic Surgery - Cosmetic",
        "Plastic Surgery - Reconstructive",
        "Printing - Copies",
        "Printing - Invitations",
        "Private Investigation",
        "RV Sales & Service",
        "Reception Halls",
        "Rentals - Cars",
        "Rentals - Equipment",
        "Rentals - Parties",
        "Rentals - Trucks",
        "Rentals - Vans",
        "Resume Services",
        "Roof Ice/Snow Removal",
        "Roofing",
        "Secretarial Services",
        "Sewing Machine Repair",
        "Sharpening",
        "Shoe Repair",
        "Signs",
        "Skin & Body Care - Day Spa Services",
        "Skin & Body Care - Vein Treatment",
        "Special Events",
        "Stereo & Home Theater Systems",
        "Storage Facilities",
        "TV Antenna",
        "TV Repair",
        "TV Sales",
        "TV Service - Cable",
        "TV Service - Satellite",
        "Tablepads",
        "Tanning Salons",
        "Tattoos/Piercings",
        "Taxi/Shuttle Service",
        "Ticket Broker Service",
        "Toy Repair",
        "Travel Agencies",
        "Trophy Shops",
        "Tutoring",
        "Tuxedo Rental",
        "Upholstering - Boat & Auto",
        "Upholstering - General",
        "Upholstery Cleaning",
        "VCR Repair",
        "Vacuum Cleaners",
        "Video Duplication & Transfer",
        "Video Production",
        "Voice Mail",
        "Warranty Companies - Non-Home",
        "Watch Repair",
        "Water Coolers",
        "Website Design & Development",
        "Wedding Planning",
        "Welding",
        "Window Cleaning"
    );

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
        foreach (array_unique($this->services) as $service){
            Service::create(array('name'=>$service));
        }
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		foreach (array_unique($this->services) as $service){
            $row = Service::where('name','=',$service);
            $row->delete();
        }
	}

}
